app:
    resource: "@AppBundle/Controller/"
    type:     annotation

# app/config/routing.yml
easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/"
    type:     annotation
    prefix:   /admin
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"